/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CreateCompositionRequest = IDL.Record({
  'title' : IDL.Text,
  'lyrics' : IDL.Text,
});
export const CompositionId = IDL.Nat;
export const Composition = IDL.Record({
  'id' : CompositionId,
  'title' : IDL.Text,
  'lyrics' : IDL.Text,
  'createdAt' : IDL.Int,
  'audioUrl' : IDL.Opt(IDL.Text),
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'createComposition' : IDL.Func([CreateCompositionRequest], [Composition], []),
  'deleteComposition' : IDL.Func([CompositionId], [IDL.Bool], []),
  'getComposition' : IDL.Func(
      [CompositionId],
      [IDL.Opt(Composition)],
      ['query'],
    ),
  'listCompositions' : IDL.Func([], [IDL.Vec(Composition)], ['query']),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateCompositionTitle' : IDL.Func(
      [CompositionId, IDL.Text],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CreateCompositionRequest = IDL.Record({
    'title' : IDL.Text,
    'lyrics' : IDL.Text,
  });
  const CompositionId = IDL.Nat;
  const Composition = IDL.Record({
    'id' : CompositionId,
    'title' : IDL.Text,
    'lyrics' : IDL.Text,
    'createdAt' : IDL.Int,
    'audioUrl' : IDL.Opt(IDL.Text),
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'createComposition' : IDL.Func(
        [CreateCompositionRequest],
        [Composition],
        [],
      ),
    'deleteComposition' : IDL.Func([CompositionId], [IDL.Bool], []),
    'getComposition' : IDL.Func(
        [CompositionId],
        [IDL.Opt(Composition)],
        ['query'],
      ),
    'listCompositions' : IDL.Func([], [IDL.Vec(Composition)], ['query']),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateCompositionTitle' : IDL.Func(
        [CompositionId, IDL.Text],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };